src/Entity/Status.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StatusRepository")
 */
class Status
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $a_vue;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $veut_voir;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="statuses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Film", inversedBy="statues_film")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_film;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAVue(): ?bool
    {
        return $this->a_vue;
    }

    public function setAVue(?bool $a_vue): self
    {
        $this->a_vue = $a_vue;

        return $this;
    }

    public function getVeutVoir(): ?bool
    {
        return $this->veut_voir;
    }

    public function setVeutVoir(?bool $veut_voir): self
    {
        $this->veut_voir = $veut_voir;

        return $this;
    }

    public function getIdUtilisateur(): ?Utilisateur
    {
        return $this->id_utilisateur;
    }

    public function setIdUtilisateur(?Utilisateur $id_utilisateur): self
    {
        $this->id_utilisateur = $id_utilisateur;

        return $this;
    }

    public function getIdFilm(): ?Film
    {
        return $this->id_film;
    }

    public function setIdFilm(?Film $id_film): self
    {
        $this->id_film = $id_film;

        return $this;
    }

}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Film;
use App\Repository\GenreRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{

    private $genreRepository;

    public function __construct(GenreRepository $genreRepository)
    {
     $this->genreRepository = $genreRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre',TextType::class,['label' => 'Titre',])
            ->add('synopsis',HiddenType::class,['label' => 'Synopsis'])
            ->add('affiche',TextType::class)
            ->add('date',DateType::class,[
                'widget' => 'single_text',
                'label' => 'Date de Sortie'
            ])
            ->add('duree',NumberType::class,['label' => 'Durée'])
            ->add('nationalite',TextType::class,['label' => 'Nationalité'])
            ->add('legislation',ChoiceType::class,[
                'choices' => [
                    'Tous Publics' => 0,
                    'Interdit -10 ans' => 10,
                    'Interdit -12 ans' => 12,
                    'Interdit -16 ans' => 16,
                    "Interdit -18 ans" => 18
                ],
                'expanded' => false,
                'multiple' => false,
                'label' => "Limite d'âge"
            ])
            ->add('trailer',TextType::class,[
                'label' => 'Bande Annonce'
            ])
            ->add('genre',TextType::class,[
                "mapped" => false
            ])
            ->add('real',TextType::class,["mapped" => false, "label" => "Réalisateur"])
            ->add('scen',TextType::class,["mapped" => false, "label" => "Scénariste"])
            ->add('act',TextType::class,["mapped" => false, "label" => "Acteur"])
        ;

        
        $builder->addEventListener(FormEvents::PRE_SUBMIT,function (FormEvent $event){
         
            $form = $event->getForm();
            $data = $event->getData();
            dump($data);
            dump($form);
            
              
            //$form->getData()->setTitre($data["titre"]);
            //$form->getData()->setSynopsis($data["synopsis"]);
            //dump($data["date"]);
            //$form->getData()->setDate(\DateTime::createFromFormat('yyyy-mm-dd',$data["date"]));
           

        });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Film::class,
        ]);
    }
}

src/Controller/FilmController.php
<?php

namespace App\Controller;

use App\Entity\Acteur;
use App\Entity\Commentaire;
use App\Entity\Film;
use App\Entity\Genre;
use App\Entity\Realisateur;
use App\Entity\Scenariste;
use App\Entity\Status;
use App\Form\CommentaireType;
use App\Repository\FilmRepository;
use App\Form\FilmType;
use App\Repository\ActeurRepository;
use App\Repository\CritiqueRepository;
use App\Repository\GenreRepository;
use App\Repository\RealisateurRepository;
use App\Repository\ScenaristeRepository;
use App\Repository\StatusRepository;
use App\Repository\UtilisateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\Request;

class FilmController extends AbstractController
{

    /**
     * @Route("/film/{slug}", name="details_film")
     */
    public function voir($slug,FilmRepository $filmRepository,Request $request,StatusRepository $statusRepository)
    {

        $film = $filmRepository->findOneBy(["slug" => $slug]);
        $user = $this->getUser();
        $commentaire = new Commentaire();

        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager = $this->getDoctrine()->getManager();

            $film->addCommentaire($commentaire);
            $user->addCommentaire($commentaire);

            $manager->persist($commentaire);
            $manager->flush();

            return $this->redirectToRoute('details_film', ['slug' => $slug]);
        }
        
        if ($user){
        $status = $statusRepository->findByDoubleId($user->getId(),$film->getId());

        if ($status){
            if ($status->getVeutVoir())
            $boutonVeutVoirEnabled = false;
            else
            $boutonVeutVoirEnabled = true;
            if ($status->getAVue()){
            $boutonAVuEnabled = false;
            $boutonVeutVoirEnabled = false;
            }
            else
            $boutonAVuEnabled = true;
        }
        else{
            $boutonVeutVoirEnabled = true;
            $boutonAVuEnabled = true;
        }
    }
    else{
        $boutonAVuEnabled = null;
        $boutonVeutVoirEnabled = null;
    }

        return $this->render('film/voir.html.twig',[
            "film" => $film,
            'form' => $form->createView(),
            "enabledVeutVoir" => $boutonVeutVoirEnabled,
            "enabledAVu" => $boutonAVuEnabled
        ]);
    }

     /**
     * @Route("/{username}/myFilms/ajouter-a-voir/{slug}", name="ajouter_aVoir")
     */
    public function addToSee($username,$slug,FilmRepository $filmRepository,UtilisateurRepository $utilisateurRepository,StatusRepository $statusRepository){

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->getUser()->getUsername() !== $username)
        return $this->redirectToRoute('welcome');
        if (!$this->getUser()->getBan())
        return $this->redirectToRoute('app_logout');

        $film = $filmRepository->findOneBy(["slug" => $slug]);

        $user = $utilisateurRepository->findOneBy(["username" => $username]);

        $status = $statusRepository->findByDoubleId($user->getId(),$film->getId());

        $manager = $this->getDoctrine()->getManager();

        if ($status){
            $status->setVeutVoir(true);
            
           $manager->persist($status);
           $manager->flush();
        
        }
        else{
            $status = new Status();
            $status->setVeutVoir(true);
            $status->setAVue(false);
            $user->addStatus($status);
            $film->addStatuesFilm($status);
            $manager->persist($status);
            $manager->flush();
        }

        $flashbag = $this->get('session')->getFlashBag();
        $flashbag->get("new");
        $flashbag->add("new",$film->getId());

        return $this->redirectToRoute('films_utilisateur',['username' => $username]);


    }

     /**
     * @Route("/{username}/myFilms/ajouter-a-vu/{slug}", name="ajouter_aVu")
     */
    public function addHasSeen($username,$slug,FilmRepository $filmRepository,UtilisateurRepository $utilisateurRepository,StatusRepository $statusRepository){

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->getUser()->getUsername() !== $username)
        return $this->redirectToRoute('welcome');
        if (!$this->getUser()->getBan())
        return $this->redirectToRoute('app_logout');

        $film = $filmRepository->findOneBy(["slug" => $slug]);

        $user = $utilisateurRepository->findOneBy(["username" => $username]);

        $status = $statusRepository->findByDoubleId($user->getId(),$film->getId());

        $manager = $this->getDoctrine()->getManager();

        if ($status){
            $status->setAVue(true);
            $status->setVeutVoir(false);
            
           $manager->persist($status);
           $manager->flush();
        
        }
        else{
            $status = new Status();
            $status->setVeutVoir(false);
            $status->setAVue(true);
            $user->addStatus($status);
            $film->addStatuesFilm($status);
            $manager->persist($status);
            $manager->flush();
        }

        $this->get('session')->getFlashBag()->clear();

        return $this->redirectToRoute('films_utilisateur',['username' => $username]);


    }


    /**
     * @Route("/{username}/myFilms/supprimer/{slug}",name="supprimer_filmfromcollection")
     */
    public function deleteFromCollection($username,$slug,FilmRepository $filmRepository,UtilisateurRepository $utilisateurRepository,StatusRepository $statusRepository){

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->getUser()->getUsername() !== $username)
        return $this->redirectToRoute('welcome');
        if (!$this->getUser()->getBan())
        return $this->redirectToRoute('app_logout');

        $film = $filmRepository->findOneBy(["slug" => $slug]);

        $user = $utilisateurRepository->findOneBy(["username" => $username]);

        $status = $statusRepository->findByDoubleId($user->getId(),$film->getId());

        $manager = $this->getDoctrine()->getManager();

        $manager->remove($status);
        $manager->flush();

        $this->get('session')->getFlashBag()->clear();

        return $this->redirectToRoute('films_utilisateur',['username' => $username]);
    }



    /**
     * @Route("/{username}/myFilms",name="films_utilisateur")
     */
    public function showMyFilms($username,UtilisateurRepository $utilisateurRepository,FilmRepository $filmRepository){

        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        if ($this->getUser()->getUsername() !== $username)
        return $this->redirectToRoute('welcome');
        if (!$this->getUser()->getBan())
        return $this->redirectToRoute('app_logout');

        $user = $utilisateurRepository->findOneBy(["username" => $username]);

        $filmsCarrTemp = [];
        $filmsCarr = [];
        $tabIdsAVu = [];
        $filmsAVu = [];
        $tabIdsVeutVoir = [];
        $filmsVeutVoir = [];

        $temp = $user->getStatuses();
        foreach($temp as $t){
            if ($t->getAVue()){
            $tabIdsAVu []= $t->getIdFilm();
            }
            if ($t->getVeutVoir()){
            $tabIdsVeutVoir []= $t->getIdFilm();
            $filmsCarrTemp []= $t->getIdFilm();
            }
        }
        shuffle($filmsCarrTemp);
        if(count($filmsCarrTemp)<7){
            for ($i=0; $i < count($filmsCarrTemp); $i++) { 
                $filmsCarr []= $filmRepository->find($filmsCarrTemp[$i]);
            }
        }
        else{
            for ($i=0; $i < 7; $i++) { 
                $filmsCarr []= $filmRepository->find($filmsCarrTemp[$i]);
            }
        }

       foreach ($tabIdsAVu as $idAVu) {
           $filmsAVu []= $filmRepository->find($idAVu);
       }

       foreach ($tabIdsVeutVoir as $idVeutVoir){
           $filmsVeutVoir []= $filmRepository->find($idVeutVoir);
       }


        return $this->render('film/myfilms.html.twig',[
            "user" => $user,
            "filmsCarr" => $filmsCarr,
            "filmsAVu" => $filmsAVu,
            "filmsVeutVoir" => $filmsVeutVoir
        ]);

    }

    //Partie Admin


    //Page de Confirmation de la Suppression des Films

    /**
     * @Route("/admin/cdf/{id}", name="admin_confirmfilmdelete")
     */
    public function filmConfirmSuppr($id,CritiqueRepository $critiqueRepository)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

       $film = $this->getDoctrine()
            ->getRepository(Film::class)
            ->find($id);


        $notification = $critiqueRepository->findCountSubmittedCritiques();
        return $this->render('admin/suppression/deleteFilm.html.twig', [
            'film' => $film,
            'notification' => $notification
        ]);
    }

    //Suppression des Films

    /**
     * @Route("/admin/cdf/{id}/delete", name="film_delete")
    */
    public function filmDelete(Film $film)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($film);
        $entityManager->flush();

        return $this->redirectToRoute('admin',['page' => 1]);
    }

    //Affichage Formulaire Modification

    /**
     * @Route("/admin/modifierfilm/{id}", name="film_modifier")
    */
    public function filmFormModif($id, Request $request, Film $movie,CritiqueRepository $critiqueRepository)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');

        $form = $this->createForm(FilmType::class, $movie);
        $form->handleRequest($request);
        
        $film = $this->getDoctrine()
            ->getRepository(Film::class)

templates/film/detailCritique.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Critiques de {{ film.titre }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/csscontenu/contenucritique.css') }}">
<style>
    .backgrounddynamique {
        background:url({{ 'http://image.tmdb.org/t/p/w780/'~film.affiche }});
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>
{% endblock %}

{% block body %}
{% if film.affiche == null %}

<body class="background">
    {% else %}

    <body class="backgrounddynamique">
        {% endif %}

        <h1 class="font size color textc margintop">AfterWatch</h1>

        <main class="main flex flexd marget bk width margina">
            <a href="{{ path('critiques', { slug: film.slug }) }}"><button class="btn btn-color">précedent</button></a>
            <section class="marget margina">
                <!--section qui comprend la carte du film-->
                <div class="card mb-3 margint" style="max-width: 540px;">
                    <div class="row no-gutters">
                        <div class="col-md-4">
                            <img src="{% if film.affiche %}{{ 'http://image.tmdb.org/t/p/w780/'~film.affiche }}{% else %}{{ asset('img/popcorn.jpg') }}{% endif %}" class="card-img"
                                alt="Affiche du Film {{ film.titre }}">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h4 class="card-title">{{ film.titre }}</h4>
                                <p class="card-text"><span class="gras">Synopsis :</span> {{ film.synopsis }}</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--section qui comprend Le nom et le titre et la critique-->
            <section class="margintop margina width">
                <article class="marginb">
                    <h5 class="margint flex jcenter">{{ critique.titre }}</h5>
                    <h6 class="margintop flex jcenter">Auteur: {{ critique.idUtilisateur.username }}</h6>
                    <div class="flex jcenter marginb stars" value="{{ critique.note }}">
                        <div class="note">{{ critique.note }}</div>
                    </div>
                    <p class="card-text sizing justify margina width ligne">
                        {{ critique.contenu }}
                    </p>
                </article>
            </section>
        </main>

        {% endblock %}

        {% block javascripts %}
        {{ parent() }}
        <script src="{{ asset('js/utilisateur/critique-stars.js') }}"></script>
        {% endblock %}

templates/film/listeCritique.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Critiques de {{ film.titre }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{ asset('css/bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/csscontenu/contenucritique.css') }}">
<style>
    .backgrounddynamique {
        background:url({{ 'http://image.tmdb.org/t/p/w780/'~film.affiche }});
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>
{% endblock %}

{% block body %}
{% if film.affiche == null %}

<body class="background">
    {% else %}

    <body class="backgrounddynamique">
        {% endif %}

        <section>

            <h1 class="font size color textc margintop">AfterWatch</h1>

            <main class="flex flexd bk width margina">
                <a href="{{ path('details_film', { slug: film.slug }) }}"><button class="btn btn-color">précedent</button></a>
                <section class="margintop margina">
                    <div class="card mb-4 margint" style="max-width: 540px;">
                        <div class="row no-gutters">
                            <div class="col-md-4">
                                <img src="{% if film.affiche %}{{ 'http://image.tmdb.org/t/p/w780/'~film.affiche }}{% else %}{{ asset('img/popcorn.jpg') }}{% endif %}" class="card-img"
                                    alt="Affiche du Film {{ film.titre }}">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h4 class="card-title">{{ film.titre }}</h4>
                                    <p class="card-text"><span class="gras">Synopsis :</span> {{ film.synopsis }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="flex jcenter margintop">
                        <a href="{% if not app.user %}{{ path('app_login') }}{% else %}{{ path('ajout_critique', { slug: film.slug }) }}{% endif %}"><button type="button"
                                class="btn btn-color marginr">Ajouter une Critique</button></a>
                    </div>
                </section>
                {% for message in app.flashes('submitted') %}
                    <div class="bg-info">{{ message }}</div>
                {% endfor %}
                <section class="margintop margina width">
                    {% for critique in film.critiques %}
                    {% if critique.publication == 1 %}
                    <article class="marginb">
                        <hr>
                        <div>
                            <a class=" flexd textalign"
                                href="{{ path('critiqueview', {slug: film.slug, slug2: critique.slug }) }}">
                                <p>Tout voir</p>
                            </a>
                        </div>
                        <div class="marginb margint flex flexdr">
                            <div class="flex flexd w-100">
                                <h6 class="margina marginb"><a
                                        href="{{ path('critiqueview', {slug: film.slug, slug2: critique.slug }) }}">{{ critique.idUtilisateur.username }}
                                        ~ {{ critique.titre }}</a></h6>
                                <p class="card-text sizing margina width ligne">
                                    {% if critique.contenu|length > 80 %}{{ critique.contenu|slice(0,79) }}(...){% else %}{{ critique.contenu }}{% endif %}
                                </p>
                                <div class="flex jend stars" value="{{ critique.note }}">
                                    <div class="note">{{ critique.note }}</div>
                                </div>
                            </div>
                        </div>
                    </article>
                    {% else %}

                    {% endif %}
                    {% endfor %}
                </section>
            </main>
    </body>
    {% endblock %}

    {% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/utilisateur/critique-stars.js') }}"></script>
    {% endblock %}

templates/film/voir.html.twig
{% extends "base.html.twig" %}

{% block title %}{{ parent() }} - Informations sur le film {{ film.titre }}{% endblock %}

{% block stylesheets %}

<link rel="stylesheet" href="{{ asset('css/bootstrap/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('css/csscontenu/contenuvoirfilm.css') }}">
<style>
  .backgrounddynamique {
    background: url({{ 'http://image.tmdb.org/t/p/w780/'~film.affiche }});
    background-size: cover;
    background-repeat: no-repeat;
  }
</style>
{% endblock %}

{% block body %}

{% if film.affiche == null %}

<body class="background">
  {% else %}

  <body class="backgrounddynamique">
    {% endif %}

    <!--<section>
  <video
    poster="{% if film.affiche %}{{ 'http://image.tmdb.org/t/p/w780/'~film.affiche }}{% else %}{{ asset('img/godzi2.jpg') }}{% endif %}"
    id="bgvid" playsinline autoplay muted loop>
</section>-->


    <div class="b-annonce">
      {% if film.trailer %}
      <iframe src='{{ 'https://youtube.com/embed/'~film.trailer }}' style='width:640px; height:360px;'
        scrolling='no'></iframe>
      {% endif %}
    </div>

    <div id="films">
      <div class="flexbutton">
        
          {% if app.user %}
          {% if enabledVeutVoir %}
          <a class="film_a_voir button btn"
            href="{{ path('ajouter_aVoir',{username: app.user.username,slug: film.slug}) }}">Je veux voir</a>
          {% endif %}
          {% if enabledAVu %}
          <a class="film_vu button btn"
            href="{{ path('ajouter_aVu',{username: app.user.username,slug: film.slug}) }}">J'ai vu</a>
          {% endif %}
          {% endif %}
          <a class="button btn flexbutton" href="{{ path('welcome') }}">Retour à l'accueil</a>
        
      </div>

      <section class="infos">
        <h1>{{ film.titre }}</h1>
        <article>
          <p><strong>Réalisateur(s):
            </strong>{% if film.realise|length > 0 %}{% for director in film.realise %}{% if loop.index == 1 %}{{ director.nom }}{% else %}
            / {{ director.nom }}{% endif %}{% endfor %}{% else %}Inconnu{% endif %}</p>
          <p><strong>Synopsis: </strong>{{ film.synopsis }}</p>
          <p><strong>Année: </strong>{{ film.date|date('Y') }}</p>
          <p><strong>Durée: </strong>{% if film.duree %}{{ film.duree // 60 }}h
            {{ film.duree % 60 }}mn{% else %}Inconnue{% endif %}</p>
          <p><strong>Nationalité: </strong>{% if film.nationalite %}{{ film.nationalite }}{% else %}Inconnue{% endif %}
          </p>
          <p><strong>Genre:
            </strong>{% if film.genreFilm|length > 0 %}{% for genre in film.genreFilm %}{% if loop.index == 1 %}{{ genre.type }}{% else %}
            / {{ genre.type }}{% endif %}{% endfor %}{% else %}Inconnu{% endif %}</p>
          <p><strong>Scénariste(s):
            </strong>{% if film.scenario|length > 0 %}{% for scen in film.scenario %}{% if loop.index == 1 %}{{ scen.nom }}{% else %}
            / {{ scen.nom }}{% endif %}{% endfor %}{% else %}Inconnu{% endif %}</p>
          <p><strong>Acteur(s):
            </strong>{% if film.acteurJoue|length > 0 %}{% for actor in film.acteurJoue %}{% if loop.index == 1 %}{{ actor.nom }}{% else %}
            / {{ actor.nom }}{% endif %}{% endfor %}{% else %}Inconnu{% endif %}</p>
        </article>
      </section>

      <section class="critique">
        <h2>Critiques</h2>
        <div class="button">
          <a class="a-voir" href="{{ path('critiques', {slug: film.slug}) }}" type="button">Voir les critiques</a>
        </div>

      </section>

      <section id="commentaire">
        <h2>Commentaires</h2>
        {% if app.user %}
        {{ form_start(form, {'attr': {'class': ' test form margint'}}) }}
        {{ form_errors(form.contenu) }}
        {{ form_widget(form.contenu, {'attr': {'class': 'form-control'}}) }}
        <button type="submit">Envoyer le Commentaire</button>
        {{ form_end(form) }}
        {% endif %}

        {% for comment in film.commentaires %}
        <article class="marginb">
          <hr>
          <div class="marginb flex flexdr">
            <div>
              <img class='avatar'
                src="{% if comment.idUtilisateur.avatar %}{{ asset('img/avatar/'~comment.idUtilisateur.avatar ) }}{% else %}{{ asset('img/avatar/utilisateur.png') }}{% endif %}"
                class="avatar">
            </div>
            <div class="flex flexd">
              <h6 class="margint marginle">de : {% if comment.idUtilisateur.roles[0] == 'ROLE_ADMIN' %}
                (Admin){% endif %}{{ comment.idUtilisateur.username }}</h6>
              <p class="card-text sizing justify marginle width ligne">
                {{ comment.contenu }}
              </p>
            </div>
          </div>
        </article>
        {% endfor %}

      </section>
    </div>
    {% endblock %}